name: Telegram payment post scheduler

on:
  schedule:
    - cron: "0 */6 * * *"  # раз в 6 часов = 4 раза в день
  workflow_dispatch:

jobs:
  ping-cron-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call Deno Deploy cron endpoint
        run: |
          curl -sS "https://mueller-payment-62.deno.dev/cron?secret=${CRON_SECRET}"
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
